/*
 * Robyn Brandner, Project Euler Problem 2
 */
package pe1;

/**
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * @author Brandner
 */
public class PE2 {
    public static long fib(long n)
    {
        long prev1 = 0;
        long prev2 = 1; 
        for(int i = 0; i<n; i++)
        {
            long savePrev = prev1;
            prev1 = prev2;
            prev2 = savePrev + prev2;
        }
        return prev1;
    }

    public static void main(String args[])
    {
        long retfib = 0;
        long sum = 0;
 
        for(long i = 0;retfib < 4000000; i++)
        {          
            retfib = fib(i);
            if(retfib % 2 == 0)
            {
                sum += retfib;
            }
        }
        System.out.println(sum);
    }   
}
